version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    # image: alkrauss48/thecodeboss.dev-db:latest
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_ROOT_PASSWORD"
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USER"
      MYSQL_PASSWORD: "$DB_PASSWORD"

  wordpress:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    # image: alkrauss48/thecodeboss.dev:latest
    volumes:
      - ./src/theme:/var/www/html/wp-content/themes/the_societea
      - ./volumes/wordpress/uploads:/var/www/html/wp-content/uploads
      - ./volumes/wordpress/plugins:/var/www/html/wp-content/plugins
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "$DB_USERNAME"
      WORDPRESS_DB_PASSWORD:  "$DB_PASSWORD"
      WORDPRESS_DB_NAME: "$DB_DATABASE"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    # image: alkrauss48/thecodeboss.dev-frontend:latest
    ports:
      - "8000:80"
    volumes:
      - ./dist:/var/www/html/dist
      - ./src/theme:/var/www/html/wp-content/themes/the_societea
      - ./volumes/wordpress/uploads:/var/www/html/wp-content/uploads
      - ./volumes/wordpress/plugins:/var/www/html/wp-content/plugins
volumes:
  db:
