version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_ROOT_DATABASE"
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USERNAME"
      MYSQL_PASSWORD: "$DB_PASSWORD"

  wordpress:
    depends_on:
      - db
    build: .
    volumes:
      - ./src/theme:/var/www/html/wp-content/themes/the_societea
      - ./dist:/var/www/html/dist
      - ./volumes/wordpress/uploads:/var/www/html/wp-content/uploads
      - ./volumes/wordpress/plugins:/var/www/html/wp-content/plugins
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "$DB_USERNAME"
      WORDPRESS_DB_PASSWORD:  "$DB_PASSWORD"
      WORDPRESS_DB_NAME: "$DB_DATABASE"
volumes:
  db:
